### ISSUE TITLE
Use of package name org.apache.pekko.sensors

### ISSUE THREAD

**Issue by pjfanning** [jacum/pekko-sensors#1]
It is generally accepted that a library's package name should be based on ownership of a related hostname. If you or your company owns 'acme.io' then you can use 'io acme' as a package name.

pekko.apache.org is owned by Apache Software Foundation. Generally, only ASF libraries can use org.apache.pekko packages.

I can accept that maybe you need access to some package private code in the Apache Pekko libs but that could be done by having a small number of org.apache.pekko.sensors classes and having the rest of your classes in package names outside the org.apache.pekko package.

**Comment by jacum** [comment]
https://github.com/jacum/pekko-sensors/pull/2 hope this would be enough
there are quite a handful of files using internal APIs

**Comment by jacum** [comment]
<img width="391" alt="image" src="https://github.com/jacum/pekko-sensors/assets/503354/eafebdd1-946b-41b0-bc4d-e05adce0e16a">

**Comment by pjfanning** [comment]
I still don't think the code goes far enough in moving code away from org.apache.pekko.sensors package.

These 2 classes in particular will cause confusion. 
```
     type = "org.apache.pekko.sensors.dispatch.InstrumentedDispatcherConfigurator"
      executor = "org.apache.pekko.sensors.dispatch.InstrumentedExecutor"
```

I have experience in OSS communities where the community continually has to redirect confused users to the different community that has abused the package names of the first community.

**Comment by jacum** [comment]
@pjfanning:
Unfortunately, if moved to another package, `InstrumentedDispatcherConfigurator` and `InstrumentedExecutor` will lose access to private classes from `org.apache.pekko.dispatch` package, e.g. `Batchable` and `Mailbox`.

**Comment by jacum** [comment]
Thanks a lot for your PR! missed it initially.

**Comment by jacum** [comment]
I assume this could be closed now.
